# NumPy Basics <hr style="border:2.5px solid #126782\"></hr>

# Data Analys: John Lester A. Acaso <br> Department: Electrical Engineering

# Install and update NumPy

In [1]:
#%pip install numpy --upgrade

# Install and update scipy

In [2]:
#%pip install scipy --upgrade

In [3]:
#%pip install numpy

In [4]:
#%pip install scipy

In [5]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [6]:
# 1-dimentional array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [7]:
# size of an array
np.shape(array_a)

(3,)

In [8]:
# 1-dimentional array
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

# 2D Array

In [9]:
# 2-dimentional array
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# size of matrix
np.shape(my_array)

(2, 3)

In [11]:
# transpose of a matrix
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
# size of matrix 
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

# Fruit Price List

In [13]:
# fruit price list dataset
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [14]:
# mean 
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [15]:
# median
fruits_median = np.median(fruits)
fruits_median

np.float64(120.0)

In [16]:
# sort
fruits_sorted = np.sort(fruits)
fruits_sorted

array([ 60,  85, 120, 150, 200])

In [17]:
# mode 
stats.mode(fruits)

ModeResult(mode=np.int64(60), count=np.int64(1))

# Voltage Response

In [18]:
# voltage response dataset
voltage = np.array([
    [1,2,3,4,5,6,7,8],
    [12,5,9.1,3.3,24,18.5,15.2,np.nan],
    [2.8,4.5,6,9,11.7,14.8,17.3,20]
])
voltage

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ],
       [12. ,  5. ,  9.1,  3.3, 24. , 18.5, 15.2,  nan],
       [ 2.8,  4.5,  6. ,  9. , 11.7, 14.8, 17.3, 20. ]])

# Measures of Variability

# Exam Performance

In [19]:
# exam performance dataset
grade = np.array([3.5,6.7,7,7.4,7.8,8.2,8.5,8.8,9,9.1,9.4,9.8])
grade

array([3.5, 6.7, 7. , 7.4, 7.8, 8.2, 8.5, 8.8, 9. , 9.1, 9.4, 9.8])

# Ice Cream Price List

In [20]:
# ice cream price list dataset
price = np.array([
    [3.5,4,3.75,4.25,3.9,4.1,3.6,4.5,3.8,4.15],
    [203,232,217.5,246.5,226.2,237.8,208.8,261,220.4,240.7]
])
price

array([[  3.5 ,   4.  ,   3.75,   4.25,   3.9 ,   4.1 ,   3.6 ,   4.5 ,
          3.8 ,   4.15],
       [203.  , 232.  , 217.5 , 246.5 , 226.2 , 237.8 , 208.8 , 261.  ,
        220.4 , 240.7 ]])

# Pooled Standard Deviation

In [21]:
# battery life dataset
battery = np.array([
    ['A','A','A','A','A','B','B','B','B','B','C','C','C','C','C'],
    [12.5,12.8,12.7,13.3,12.6,13.5,14.1,13.9,14.3,13.7,11.8,11.9,12.1,12.2,11.6]
])
battery

array([['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C',
        'C', 'C'],
       ['12.5', '12.8', '12.7', '13.3', '12.6', '13.5', '14.1', '13.9',
        '14.3', '13.7', '11.8', '11.9', '12.1', '12.2', '11.6']],
      dtype='<U32')

# Assignment

# Jaguar Measures of Central Tendency

In [22]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [23]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [24]:
jaguar_median = np.median(jaguar)
jaguar_median

np.float64(9.8)

In [25]:
jaguar_mode = stats.mode(jaguar)
jaguar_mode

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [26]:
jaguar_std = np.std(jaguar)
jaguar_std

np.float64(2.101947149236112)

In [27]:
jaguar_sorted = np.short(jaguar)
jaguar_sorted

array([10,  9,  9,  9, 10, 10,  9, 11, 10,  3,  9], dtype=int16)

In [28]:
max_jaguar = np.max(jaguar)
max_jaguar

np.float64(11.0)

In [29]:
min_jaguar = np.min(jaguar)
min_jaguar

np.float64(3.0)

In [30]:
range_jaguar = max_jaguar - min_jaguar
range_jaguar

np.float64(8.0)

In [31]:
q1_jaguar = np.percentile(jaguar, 50)
q1_jaguar

np.float64(9.8)

In [32]:
q2_jaguar = np.percentile(jaguar, 50)
q2_jaguar

np.float64(9.8)

In [33]:
q3_jaguar = np.percentile(jaguar,75)
q3_jaguar

np.float64(10.45)

# Panther Measures Central Tendency

In [34]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [35]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [36]:
panther_median = np.median(panther)
panther_median

np.float64(9.55)

In [37]:
panther_mode = stats.mode(panther)
panther_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [38]:
panther_std = np.std(panther)
panther_std

np.float64(3.1582431825304393)

In [39]:
panther_sorted = np.sort(panther)
panther_sorted

array([ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9, 10.1, 10.8, 11. , 20. ])

In [40]:
max_panther = np.max(panther)
max_panther

np.float64(20.0)

In [41]:
min_panther = np.min(panther)
min_panther

np.float64(9.1)

In [42]:
range_panther = max_panther - min_panther
range_panther

np.float64(10.9)